### ISSUE TITLE
More like Eagler Reborn Reborn

### ISSUE THREAD

**Issue by radmanplays** [EaglerReborn/reborn#2]
also why is YoinkAssets.bat and YoinkAssets.sh removed from the repo?

**Comment by OtterCodes102** [comment]
its because of dmca reasons

**Comment by ZXMushroom63** [comment]
ah.

**Comment by grandpa1946** [comment]
rip productivity

**Comment by grandpa1946** [comment]
@OtterCodes102 is yoinkassets the reason of dmca?

**Comment by ZXMushroom63** [comment]
no it was copyrighted textures, which used to be in the `sources/resources/assets/minecraft` directory

**Comment by grandpa1946** [comment]
rip
