### ISSUE TITLE
[BUG] gradle hangs indefinitely on teavmc task (crashes after too)

### ISSUE THREAD

**Issue by Hellscaped** [EaglerReborn/reborn#20]
**Describe the bug**
title

**To Reproduce**
1. attempt to gradlew teavm

**Expected behavior**

**Screenshots**
![image](https://github.com/EaglerReborn/reborn/assets/72767525/b3121fd2-b707-4b2d-bba8-5f2b7a24b859)

**Browser (please complete the following information):**
 - OS: Debian
 - Browser [e.g. chrome, safari] Does not matter
 - Version [e.g. Alpha] Latest dev

**Comment by Hellscaped** [comment]
![image](https://github.com/EaglerReborn/reborn/assets/72767525/c66c5f6b-2e54-4282-b8e6-68267a33d986)

**Comment by OtterCodes102** [comment]
looks like you don't have enough RAM.

**Comment by ZXMushroom63** [comment]
You can try adding --no-daemon to the gradlew call, that helps use less ram.

**Comment by Hellscaped** [comment]
> looks like you don't have enough RAM.

It was using the devcontainer config you had, which chokeheld it. I had to wipe .devcontainer and rebuild it for eag to build

**Comment by OtterCodes102** [comment]
> > looks like you don't have enough RAM.
> 
> It was using the devcontainer config you had, which chokeheld it. I had to wipe .devcontainer and rebuild it for eag to build

i'm working on a new one, will be out soon.
