### ISSUE TITLE
[BUG] plugin api client brand is actually the server brand

### ISSUE THREAD

**Issue by OtterCodes102** [EaglerReborn/reborn#5]
**Describe the bug**
looking at the client brand via the plugin api reveals that it is actually the server brand
**To Reproduce**
1. log on to a server
2. open developer tools
3. return the plugin api client brand in console
4. it shows the server's brand instead

**Expected behavior**
it shows "reborn"

**Browser (please complete the following information):**
 - OS: ChromeOS
 - Browser: Chrome
 - Version Beta 1.1

**Comment by ZXMushroom63** [comment]
Can you give an example of what you ran in the console?

**Comment by OtterCodes102** [comment]
```js
PluginAPI.player.clientBrand
```

**Comment by ZXMushroom63** [comment]
Hmm. Looking through the code, it appears to be a bug in MC. However, I can add a property on the PluginAPI itself, which returns something from ClientBrandRetriever.java

**Comment by ZXMushroom63** [comment]
I'll keep the issue open till I implement it.

**Comment by ZXMushroom63** [comment]
Fixed (ish) in a5.1
You can retrieve the actual client brand with `PluginAPI.clientBrand`

**Comment by ZXMushroom63** [comment]
made pull for a5.1
