### ISSUE TITLE
add my jetpack plugin to the example plugins folder

### ISSUE THREAD

**Issue by radmanplays** [EaglerReborn/reborn#8]
https://github.com/radmanplays/eaglerreborn-plugins/blob/main/jetpack-v1.1.js

**Comment by ZXMushroom63** [comment]
Can you update it to use `PluginAPI.player.reload()` instead of `PluginAPI.updateComponent`

**Comment by radmanplays** [comment]
> Can you update it to use `PluginAPI.player.reload()` instead of `PluginAPI.updateComponent`

k i did

**Comment by ZXMushroom63** [comment]
ok

**Comment by ZXMushroom63** [comment]
Added your plugin as jetpack.js
Credits on first line

**Comment by radmanplays** [comment]
> Added your plugin as jetpack.js Credits on first line

thanks
